name: Debbuild

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        path: brewtarget
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'
        
    - name: Prepare utils for deb package
      uses: actions/checkout@v2
      with:
        repository: Brewtarget/debian-packaging  
        path: debian-packaging
        
    - name: Dependencies
      shell: bash
      run: sudo apt-get install -y debhelper qtbase5-dev qttools5-dev-tools qtmultimedia5-dev libqt5webkit5-dev libqt5svg5-dev lintian

    - name: Create orig
      working-directory: ${{github.workspace}}/debian-packaging
      shell: bash
      run: ./createorig.sh ../brewtarget
    
    - name: Create package
      working-directory: ${{github.workspace}}/debian-packaging/brewtarget-2.4.0
      run: dpkg-buildpackage -us -uc -d
      shell: bash

    - name: Lintian
      working-directory: ${{github.workspace}}/debian-packaging/brewtarget-2.4.0
      shell: bash
      run: lintian --pedantic *.changes | less

    - name: Upload artifacts
      working-directory: ${{github.workspace}}/debian-packaging/brewtarget-2.4.0
      shell: bash
      run: ls
