name: develop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        
      - uses: addnab/docker-run-action@v1
        with:
          image: xzfantom/mxe-qt5-cmake:1.0
          options: -v $GITHUB_WORKSPACE:/work
          run: "cd /work && ls && x86_64-w64-mingw32.shared-cmake -DMINGW_BIN_DIR=/opt/mxe/usr/x86_64-w64-mingw32.shared/bin -DCMAKE_RC_COMPILER:FILEPATH=/opt/mxe/usr/bin/x86_64-w64-mingw32.shared-windres --config Debug --target all -j4 ../ && make package"
